### ISSUE TITLE
Subject generator periodically creates subjects < 20 characters.

### ISSUE THREAD

**Issue by markjulmar** [XamarinUniversity/XAM110#1]
Easy fix - either change the generator to always be a minimum of 20 characters, or change the following code into the `GetCell` method:

*before*
```
cell.TextLabel.Text = item.Subject.Substring(0,20) + "...";
```

*after*
```
cell.TextLabel.Text = item.Subject.Substring(0,Math.Min(20,item.Subject.Length-1)) + "...";
```

**Comment by adrianstevens** [comment]
This is a fix for IOS110 - will be corrected in that repo. 

closing issue
