### ISSUE TITLE
The tutorial forgot to mention that we need to change the path.

### ISSUE THREAD

**Issue by sadqiang** [XamarinUniversity/XAM110#4]
[In this step](https://elearning.xamarin.com/forms/xam110/netstandard/exercise4-upgrade-pcl-to-netstandard/2-migrate-files), we actually need to change 

`const string ResourceName = "MyTunes.Shared.songs.json";`

to

`const string ResourceName = "MyTunes.NetStandard.songs.json";`

But the author probably forgot to mention it.

Hardcoded string is always dangerous. :-)

**Comment by patridge** [comment]
Thank you for reporting this. I confirmed it was definitely changed in the completed exercise 4 solution and adjusted the instructions to match. It should be deploying those updates soon.
